### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by termlen0**
##### SUMMARY

Replace ASCII image with PNG

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

- exercises

##### ADDITIONAL INFORMATION

Link to drawing (can be duplicated and edited if needed)
https://docs.google.com/presentation/d/1q41ccBsBoo2jcbkjtCQGniGZZALJXBcj5GpA23ueExU/edit?usp=sharing

```paste below

```

### CODE REVIEW

**Comment by IPvSean** [comment]
assigning to @liquidat , please make your titles for PRs better @termlen0 !

**Comment by liquidat** [comment]
@termlen0 Good idea, I like the graphics. Can you get me the source? I'd like to add this to the main presentation and maintain it there in an editable form (there will be updates), and just export it to the exercises.

**Comment by termlen0** [comment]
> @termlen0 Good idea, I like the graphics. Can you get me the source? I'd like to add this to the main presentation and maintain it there in an editable form (there will be updates), and just export it to the exercises.

:) Check the *Additional Information*  section in the PR

**Comment by termlen0** [comment]
> assigning to @liquidat , please make your titles for PRs better @termlen0 !

boo

**Comment by IPvSean** [comment]
Ajay FIX your PR titles

**Comment by IPvSean** [comment]
@liquidat any reason this can't get merged?

**Pull request merged**
