### PR TITLE
change Machine credential details

### PR DESCRIPTION
**Pull request by ffirg**
##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
- exercises

### CODE REVIEW

**Comment by cloin** [comment]
I'm confused by this one. The previous resource names already matched what we provision as a part of all workshops, right? https://github.com/ffirg/workshops/blob/patch-6/provisioner/roles/populate_tower/tasks/main.yml

**Comment by ffirg** [comment]
Sorry I've confused you by the looks of it. Provisioning is fine, it's the exercise README that is wrong.
The exercise details state Workshop Credentials when everything else is using the Student Account that we get students to create in an earlier exercise.

**Comment by cigamit** [comment]
Another change that we need to make (and I talked to Sean about this along time ago) is have it delete the "Workshop Credential" that the provisioner creates when its a Windows workshop.  Its a duplicate as we have them create the Credential during the lesson (and Sean didn't want me to add a when statement to the create, instead wants it in the separate windows file to delete).  We should clean up the inventory items at the same time, as the -ansible host should be removed.

**Comment by cloin** [comment]
> Sorry I've confused you by the looks of it. Provisioning is fine, it's the exercise README that is wrong.
> The exercise details state Workshop Credentials when everything else is using the Student Account that we get students to create in an earlier exercise.

Ok sounds good. Can you rebase to fix conflicts and I can merge?

**Comment by ffirg** [comment]
@cloin not sure what I need to do to fix?

**Comment by IPvSean** [comment]
image

**Comment by cloin** [comment]
@ffirg it's just to clear up this conflict. It looks like once that conflict is resolved we can merge.

Conflicting files
exercises/ansible_windows/8-chocolatey/README.md

**Comment by cloin** [comment]
recheck

**Pull request merged**
