### PR TITLE
Move connectivity check back to EC2 role

### PR DESCRIPTION
**Pull request by cigamit**
##### SUMMARY
According to the text of the connectivity_test role, Sean seems to be expressing a desire to move the connectivity checking back to the manage_ec2_instances role.  This PR does that.  Networking uses a wait_for check, so I moved that check also.

Text from connectivity_check role

> This wait_for_connection task can't be part of manage_ec2_instances
> because you can't use groups with delegate_to, see: (removed URL)
> also the meta refresh_inventory won't help, as its intended for dynamic inventory

Personally, I would rather we keep it as a separate role, as it is slightly faster because of forking.  In the end you are always going to wait for them all, so not sure it really matters.  I created this PR just in case Sean still desires to move it for other reasons, otherwise feel free to close it.

We could move the connection check into its own file if desired in this role also (but having only 2 tasks in a file seems wasteful when you then have to run an extra task to include them).

I also noticed that the Windows workshop was double checking connectivity, so removed that.  Security workshop wasn't checking for connectivity on the windows workstation.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
Tested against both windows, networking, and security workshops.
**Networking**
```
TASK [manage_ec2_instances : check connectivity to all nodes (excluding routers)] *****************************************************************************************************************************
ok: [localhost -> 3.95.37.251] => (item=JCONNER-CONNECTN-student1-ansible)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-rtr1)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-rtr2)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-rtr3)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-rtr4)
skipping: [localhost] => (item=localhost)

TASK [manage_ec2_instances : check connectivity to all routers] ***********************************************************************************************************************************************
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-ansible)
ok: [localhost] => (item=JCONNER-CONNECTN-student1-rtr1)
ok: [localhost] => (item=JCONNER-CONNECTN-student1-rtr2)
ok: [localhost] => (item=JCONNER-CONNECTN-student1-rtr3)
ok: [localhost] => (item=JCONNER-CONNECTN-student1-rtr4)
skipping: [localhost] => (item=localhost)
```
**Windows**
```
TASK [manage_ec2_instances : check connectivity to all nodes (excluding routers)] *****************************************************************************************************************************
ok: [localhost -> 3.81.224.52] => (item=JCONNER-CONNECTN-student1-ansible)
ok: [localhost -> 54.226.249.79] => (item=gitlab)
ok: [localhost -> 52.87.186.156] => (item=student1-win1)
skipping: [localhost] => (item=localhost)

TASK [manage_ec2_instances : check connectivity to all routers] ***********************************************************************************************************************************************
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-ansible)
skipping: [localhost] => (item=gitlab)
skipping: [localhost] => (item=student1-win1)
skipping: [localhost] => (item=localhost)
```

**Security**
```
TASK [manage_ec2_instances : check connectivity to all nodes (excluding routers)] *****************************************************************************************************************************
ok: [localhost -> 52.73.47.121] => (item=JCONNER-CONNECTN-student1-ansible)
ok: [localhost -> 54.90.148.116] => (item=JCONNER-CONNECTN-student1-qradar)
ok: [localhost -> 34.227.242.175] => (item=JCONNER-CONNECTN-student1-attacker)
ok: [localhost -> 52.54.170.105] => (item=JCONNER-CONNECTN-student1-snort)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-checkpoint_mgmt)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-checkpoint_gw)
ok: [localhost -> 54.236.217.68] => (item=JCONNER-CONNECTN-student1-windows_ws)
skipping: [localhost] => (item=localhost)

TASK [manage_ec2_instances : check connectivity to all routers] ***********************************************************************************************************************************************
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-ansible)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-qradar)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-attacker)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-snort)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-checkpoint_mgmt)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-checkpoint_gw)
skipping: [localhost] => (item=JCONNER-CONNECTN-student1-windows_ws)
skipping: [localhost] => (item=localhost)
```

### CODE REVIEW

**Comment by Spredzy** [comment]
F5 workshops are failing on the wait for command

```
failed: [localhost -> 13.230.161.160] (item=tqe-gating-mbhkylmy-student2-f5) => changed=false 
  ansible_loop_var: item
  elapsed: 403
  item: tqe-gating-mbhkylmy-student2-f5
  msg: 'timed out waiting for ping module test success: Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in "/tmp".
failed: [localhost -> 3.112.237.31] (item=tqe-gating-mbhkylmy-student1-f5) => changed=false 
  ansible_loop_var: item
  elapsed: 400
  item: tqe-gating-mbhkylmy-student1-f5
  msg: 'timed out waiting for ping module test success: Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in "/tmp". 
ok: [localhost -> 52.195.3.195] => (item=tqe-gating-mbhkylmy-student1-node1)
ok: [localhost -> 54.249.35.59] => (item=tqe-gating-mbhkylmy-student2-node1)
ok: [localhost -> 13.231.180.73] => (item=tqe-gating-mbhkylmy-student2-node2)
ok: [localhost -> 54.238.178.200] => (item=tqe-gating-mbhkylmy-student1-node2)
skipping: [localhost] => (item=localhost) 
```

**Comment by cigamit** [comment]
Ya, I am thinking an easier way to do this is to add a connectivity group to each host that tells it which check it should be doing to test connectivity (if any).  Otherwise the amount of when statements is only going to grow as we add more workshops that their own exceptions in them.

**Comment by cigamit** [comment]
recheck

**Comment by IPvSean** [comment]
won't we lose parallelism though?  would it make more sense to have a 

include_playbook: {{workshop_type}}.yml in the wait_for_connection role?

@cloin @liquidat cc

**Comment by cigamit** [comment]
Yep, which is why I said "the current way is faster because of forking" but I was just going off your comment in the connection role.  Still might be a good idea to do special groups for the hosts that need connections (like the last commit) so we can more easily define those, and we can start doing port checks on the other devices (like the F5s) that currently have no check at all applied to them.

**Comment by cigamit** [comment]
If you decide this should stay its own role, then I can rework the connectivity role to be more generic and work off of groups, so that each workshop doesn't have to supply its own file, only add the appropriate group to each host.

**Comment by cigamit** [comment]
F5 one failed on the teardown with with 
```

2020-04-01 16:36:43.928106 \| centos-8 \| TASK [manage_ec2_instances : Delete subnet for tqe-gating-avfbpfwk-vpc] ********
--
1977 | 2020-04-01 16:36:56.462200 \| centos-8 \| An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://ec2.ap-northeast-1.amazonaws.com/"
1978 | 2020-04-01 16:36:56.465898 \| centos-8 \| fatal: [localhost]: FAILED! => changed=false
1979 | 2020-04-01 16:36:56.465961 \| centos-8 \|   boto3_version: 1.12.33
1980 | 2020-04-01 16:36:56.466013 \| centos-8 \|   botocore_version: 1.15.33
1981 | 2020-04-01 16:36:56.466087 \| centos-8 \|   msg: 'Couldn''t get matching subnet: Could not connect to the endpoint URL: "https://ec2.ap-northeast-1.amazonaws.com/"'

```

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
I think EC2 had some issue last night. I've read here and there people complaining about havingg difficulties. Seems fixed now.

**Comment by cigamit** [comment]
I will redo this PR and leave it in the role, but will rework the connectivity check role to be more universal and add other checks.

**Pull request closed without merging**
