### PR TITLE
Add Chocolatey exercise to the Windows workshop

### PR DESCRIPTION
**Pull request by raedrizk**
##### SUMMARY
PR To add the optional Chocolatey exercise to the Windows workshop

##### ISSUE TYPE
- Exercises Pull Request

##### COMPONENT NAME
- exercises

##### ADDITIONAL INFORMATION
Changes made are:
- Adding an extra ad-hoc module to Tower
- Adding the exercise readme + images
- Adding links to the new optional exercise

### CODE REVIEW

**Comment by Spredzy** [comment]
recheck

**Comment by IPvSean** [comment]
@cloin don't we already have it?

**Comment by cigamit** [comment]
Adding an optional Chocolatey Lesson is good IMO, but adding an non-optional VM to the stack for the optional lesson is more questionable, especially when the non-optional VM is only used for about 20% of the optional lesson.

**Comment by abenokraitis** [comment]
A lab on Chocolately (in which the content is partner-supported) should be independent of the Windows workshop (which is Ansible-supported), and not required as part of the larger workshop (maybe a demo instead like other partner solutions?).

**Comment by cloin** [comment]
I like it. In my experience, Chocolatey has come up in every windows workshop that I’ve instructed while porting skylight to this repo. That said, I do see the concern in adding optional exercises that will increase the overall cost of the entire workshop. While windows is probably the cheapest workshop (each student is allotted 2 instances and there’s one share instance per workshop), it may make sense to have a new var created to provision windows workshop + chocolatey. We could easily have 2 catalog items, or implement a checkbox on the windows workshop catalog items to add in the extra instance and chocolatey roles to configure that instance. Only problem then would be docs.

**Comment by cigamit** [comment]
If we move to Provisioned Docs (discussed in another topic) then the docs wouldn't be much of an issue.

For this, I would rather we just remove the very end part of the lesson that deals with changing the chocolatey source to our own chocolatey server.  Then that drops the need for running a chocolatey server, and moves to this just being a new Optional addition to the lessons versus adding more to the provisioner.  Its just 1 VM being added per workshop not per student, but it adds up fast when you run through as many workshops as we do.  We are already looking at how to trim down other workshops to deal with hitting limits within AWS.

**Comment by cloin** [comment]
Oh I didn’t even notice that we were only using the extra instance for one exercise. I feel like we could add this as an optional exercise or add on to the workshop if we remove that. Otherwise, we could just have some var as a conditional to provision the extra instance.

**Comment by oatakan** [comment]
I think Chocolatey would be nice to have as optional. it can be set up on one of the existing non-windows hosts optionally (i.e. control host/attendance).

@raedrizk you can take a look at this non-Windows deployment options here to see if it's workable, like samba share on a linux host: https://chocolatey.org/docs/how-to-host-feed#non-windows-hosting

**Comment by raedrizk** [comment]
Thanks everyone for your input. so there are currently multiple ways to go forwards:

1. @cigamit 's suggestion which is to use the chocolatey server he mentioned  to avoid provisioning a new server per workshop:
- I don't know what that server is but will it be affected negatively by the load of the workshops?
- Will need the details to use it please (if that is the chosen direction)

2. @cloin 's suggestion to add a flag and make it an optional exercise
- will require to conditionally generate the docs to either include/exclude that exercise

3. @oatakan 's suggestion to use an existing server 
- Use the attendance host: the flag is on by default for RHPDS, but for manually provisioned workshops we could end up with a workshop without the attendance host and the exercise in place - unless we are conditionally generating the docs
- use the control host of either student 1 to serve the whole set of students, or use the control host of each student


so any feedback on the options so I could move forward? I personally am leaning towards @oatakan 's suggestion . I havnt tried the non-Windows deployment options, but hopefully they're straight forward

Thanks

**Comment by cigamit** [comment]
> I don't know what that server is but will it be affected negatively by the load of the workshops?

I didn't say to use another server, I said don't deploy the chocolatey server at all, and remove the last part of the lesson that goes over using an Internal Chocolatey server from another source.  So drop all the playbook changes and leave the doc changes.  This would effectively make this an Exercises PR instead of a Provisioner PR.

I would also agree with @oatakan approach though, just install the chocolatey server on the "attendance" host.  I just don't want a "new" server deployed that is only going to be used for 5 minutes of a lesson.

**Comment by raedrizk** [comment]
Removed exercise 3 and the additional instance per @cigamit 's suggestion above. At some point down the road will re-add using an existing instance. 
It is now an Exercises PR (Almost - only non documentation piece is an extra adhoc module added to the populate tower role)
@cloin please take a look when you have a chance

**Comment by raedrizk** [comment]
@cloin any comments on the changes?

**Pull request merged**
