### PR TITLE
Move static files and templates into subdirectory

### PR DESCRIPTION
**Pull request by mrtwnklr**
##### SUMMARY
Move static and template files into their subdirectories. The first exercises are a good starting point to teach best practices.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
- exercises

##### ADDITIONAL INFORMATION
Only the english RHEL exercise README.md files are updated. Has still to be done for the other translations.

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by IPvSean** [comment]
I am wondering if testing got stuck @Spredzy ?

**Comment by Spredzy** [comment]
@IPvSean here also all readme so you should feel free to merge if happy with content.

  * Zuul initially failed because of network issue, recheck restored status to SUCCESS
  * One workshops (security one) has had a network hiccup `msg: 'timed out waiting for ping module test success: Failed to connect to the host via ssh: ssh: connect to host 34.224.64.151 port 22: Connection timed out'`

Feel free to merge

**Comment by IPvSean** [comment]
this makes sense to me, what do you think @termlen0 , @gdykeman , @rhcreynold  @cloin , just need someone elses opinion since i don't teach this one very often

**Pull request merged**
