### PR TITLE
Set tower project call module to proper collection

### PR DESCRIPTION
**Pull request by liquidat**
##### SUMMARY

Forgot to update this module call to collections.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

- provisioner

### CODE REVIEW

**Comment by IPvSean** [comment]
recheck

**Comment by IPvSean** [comment]
recheck

**Comment by liquidat** [comment]
recheck - error is not in security

**Comment by liquidat** [comment]
recheck

**Pull request merged**
