### PR TITLE
Update windows smartconsole installer to 8040

### PR DESCRIPTION
**Pull request by liquidat**
##### SUMMARY

Update Windows SmartConsole to R80.40 - #1080 CANNOT work without this!

##### ISSUE TYPE

- Feature Request

##### COMPONENT NAME

- provisioner

### CODE REVIEW

**Comment by IPvSean** [comment]
recheck

**Comment by liquidat** [comment]
recheck
my error

**Comment by liquidat** [comment]
recheck

**Comment by liquidat** [comment]
@IPvSean 
All good, the error is not in security.

**Pull request merged**
