### PR TITLE
Add Japanese version exercises(1.1-explore/1.2-checkpoint/1.3-snort) for Ansible Security Workshop 

### PR DESCRIPTION
**Pull request by hiyokotaisa**
##### SUMMARY
Add Japanese version exercises(1.1-explore) for Ansible Security Workshop 
This is intended to add Japanese translation for Ansible Security Workshop (#910)
##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

- exercises

### CODE REVIEW

**Comment by liquidat** [comment]
@hiyokotaisa Looks good, awesome! Do you want to create multiple PRs, one for each section? Or are you adding more and more translations in this PR?

**Comment by hiyokotaisa** [comment]
@liquidat May I create multiple PR? I would like to separate the PR since body of each docs are so long so it seems it will still take time to translate all of them.

**Comment by cloin** [comment]
That sounds like a good idea. After you are finished with all translations, you could create a PR adding the links to the available translations for each exercise like we have for RHEL and others.

**Comment by cloin** [comment]
@hiyokotaisa this PR is still marked WIP. Would you like to merge now or continue working on this? If you want to hold off on merging this PR, please just tag me or @liquidat when it's ready.

**Comment by hiyokotaisa** [comment]
@cloin @liquidat Thank you for the comment! I'm okay with merging this PR now if it looks good. I translated 1.1 - 1.3 exercises.

**Pull request merged**
