### PR TITLE
Removing daemonize as dependency

### PR DESCRIPTION
**Pull request by liquidat**
##### SUMMARY

daemonize was causing many problems in our testing infrastructure. For
that reason this commit removes it from all places and instead leverage
the systemd based solutions we already had in exercise 2.2 everywhere
now.

This commit:
- adds sql and web attack simulations (start and stop) to Tower
- rewrites all exercises using those attacks to point users to Tower
  instead of launching bash scripts
- changes the tests to leverage Tower for attack execution

NOTE: merging this PR MUST include merging [this commit](https://github.com/ansible-security/workshop-examples/commit/7f014b37e8d2c833077debcb424d1cc3230db4af) into master in the repo [workshop-examples](https://github.com/ansible-security/workshop-examples).

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

- exercises
- provisioner

### CODE REVIEW

**Comment by liquidat** [comment]
@pierreblanc @senpot Please note this change: you might want to update your translations as well. Feel free to commit directly to this PR.

**Comment by senpot** [comment]
@liquidat Thank you your message. I understood this change, So I will translate it into Japanese after this PR is merged.

**Comment by cloin** [comment]
@liquidat is this ready to go?

**Comment by liquidat** [comment]
@cloin Not yet, I still want to get @Spredzy's review before we merge. And when we merge we need to do a merge of the workshop-examples at the same time!

**Comment by IPvSean** [comment]
@liquidat do you want me to test this again?

**Comment by liquidat** [comment]
@Spredzy Can you please note here if this is what you need, or not, for the tests?

**Comment by IPvSean** [comment]
you guys got an update on what this is for? @Spredzy @liquidat

**Comment by Spredzy** [comment]
Sorry hasn't answered earlier. Same reason as https://github.com/ansible/workshops/pull/754#issuecomment-777009606

**Comment by IPvSean** [comment]
and can we close this one @Spredzy ?

**Pull request closed without merging**
