### PR TITLE
QE: Add security verify exercise to zuul

### PR DESCRIPTION
**Pull request by Spredzy**

### CODE REVIEW

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
Consistently seeing the following on the logs:

```
2020-03-25 13:31:56.393932 | centos-8 | TASK [Verify attack string in log file] ****************************************
2020-03-25 13:31:58.237928 | centos-8 | FAILED - RETRYING: Verify attack string in log file (12 retries left).
2020-03-25 13:32:14.954752 | centos-8 | FAILED - RETRYING: Verify attack string in log file (11 retries left).
2020-03-25 13:32:31.667787 | centos-8 | FAILED - RETRYING: Verify attack string in log file (10 retries left).
2020-03-25 13:32:48.363523 | centos-8 | FAILED - RETRYING: Verify attack string in log file (9 retries left).
2020-03-25 13:33:05.090496 | centos-8 | FAILED - RETRYING: Verify attack string in log file (8 retries left).
2020-03-25 13:33:21.830898 | centos-8 | FAILED - RETRYING: Verify attack string in log file (7 retries left).
2020-03-25 13:33:38.544903 | centos-8 | FAILED - RETRYING: Verify attack string in log file (6 retries left).
2020-03-25 13:33:55.241691 | centos-8 | FAILED - RETRYING: Verify attack string in log file (5 retries left).
2020-03-25 13:34:11.956818 | centos-8 | FAILED - RETRYING: Verify attack string in log file (4 retries left).
2020-03-25 13:34:28.666709 | centos-8 | FAILED - RETRYING: Verify attack string in log file (3 retries left).
2020-03-25 13:34:45.387721 | centos-8 | FAILED - RETRYING: Verify attack string in log file (2 retries left).
2020-03-25 13:35:02.216724 | centos-8 | FAILED - RETRYING: Verify attack string in log file (1 retries left).
2020-03-25 13:35:18.934405 | centos-8 | fatal: [ansible]: FAILED! => changed=true
2020-03-25 13:35:18.934497 | centos-8 |   attempts: 12
2020-03-25 13:35:18.934512 | centos-8 |   cmd:
2020-03-25 13:35:18.934522 | centos-8 |   - ssh
2020-03-25 13:35:18.934530 | centos-8 |   - ec2-user@54.91.212.255
2020-03-25 13:35:18.934542 | centos-8 |   - sudo
2020-03-25 13:35:18.934551 | centos-8 |   - grep
2020-03-25 13:35:18.934560 | centos-8 |   - web_attack
2020-03-25 13:35:18.934569 | centos-8 |   - /var/log/httpd/access_log
2020-03-25 13:35:18.934578 | centos-8 |   delta: '0:00:00.414493'
2020-03-25 13:35:18.934587 | centos-8 |   end: '2020-03-25 13:35:18.728919'
2020-03-25 13:35:18.934596 | centos-8 |   msg: non-zero return code
2020-03-25 13:35:18.934605 | centos-8 |   rc: 1
2020-03-25 13:35:18.934614 | centos-8 |   start: '2020-03-25 13:35:18.314426'
2020-03-25 13:35:18.934623 | centos-8 |   stderr: ''
2020-03-25 13:35:18.934631 | centos-8 |   stderr_lines: <omitted>
2020-03-25 13:35:18.934640 | centos-8 |   stdout: ''
2020-03-25 13:35:18.934649 | centos-8 |   stdout_lines: <omitted>
```

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by IPvSean** [comment]
any update on this @liquidat ?

**Comment by Spredzy** [comment]
Sorry, not on @liquidat but on me to get back to this one. I need to make time to get back to it.

**Pull request closed without merging**
