### PR TITLE
Venv dependencies were not being replicated to cluster nodes

### PR DESCRIPTION
**Pull request by termlen0**
##### SUMMARY

The create_cluster option for the provisioner has a bug where the venvs are not being replicated to the cluster nodes. This PR fixes it.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

- provisioner

##### ADDITIONAL INFORMATION

This breaks the backup scripts during upgrades etc.

```paste below

```

### CODE REVIEW

**Comment by termlen0** [comment]
Logs appear to indicate that the tests are failing due to 
```

2020-12-13 09:30:45.002936 \| TASK [upload-logs-swift : Upload logs to swift]
--


```
Let me know how I can help.

**Comment by IPvSean** [comment]
recheck

**Comment by IPvSean** [comment]
can you rebase your fix @termlen0

**Comment by IPvSean** [comment]
recheck

**Comment by IPvSean** [comment]
error with CI testing is a limitation with AWS capacity, nothing to do with workshop provisioning code->
```
  msg: 'Instance creation failed => InsufficientInstanceCapacity: We currently do not have sufficient t2.2xlarge capacity in the Availability Zone you requested (us-east-1a). Our system will be working on provisioning additional capacity. You can currently get t2.2xlarge capacity by not specifying an Availability Zone in your request or choosing us-east-1b, us-east-1c, us-east-1d, us-east-1e, us-east-1f.'
```

merging, thanks @termlen0

**Comment by IPvSean** [comment]
thank you

**Pull request merged**
