### PR TITLE
Create a collection out of all roles.

### LINKED ISSUE #617: change workshop into an ansible collection
##### SUMMARY
change workshop into an ansible collection 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
needs a strategy, but long-term goal should be a collection versus a random github repo

### PR DESCRIPTION
**Pull request by sstanovnik**
##### SUMMARY

Converts this repository into an Ansible Collection that contains all* roles.

WIP until tests pass, obviously, since this is a huge change.

Resolves #617.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
My process was as follows, for each* role:

1. Move the role from `provisioner/roles/` to `roles/`
2. Add a `meta/argument_spec.yml` to document entrypoints and their inputs. Ansible 2.11 validates these before running the role, helping catch unpleasant errors. It also makes the documentation much fuller.
3. Update references to modules that are not `ansible.builtin` to use FQCNs.
4. Update `galaxy.yml` with any collection dependencies.
5. Update `include_role` et al references. These still use path-based referencing, not FQCNs. I'll make that a future change so fewer things break at a time.

I've also updated CI to install the collection (for its dependencies, it won't be used because there are no FQCNs) before running the tests.

\* Now for the footnote. There are two roles I haven't ported:

* `manage_ec2_instances`, because that'll become agnostic'd.
* `geerlingguy.gitlab`, because it's vendored.

The first one stays for now. The second one doesn't have a collection associated with it, so I can't put it into `galaxy.yml`'s requirements. I think the best thing to do here is to port it vendored, just as with all other roles.

What do you think, @IPvSean?

I've also made a separate commit for each role migration for clarity. Please tell me if I need to squash them or anything.

### CODE REVIEW

**Comment by IPvSean** [comment]
@sstanovnik failing CI... but I am not 100% sure what is going on.  Been talking to @pabelanger 
I made a small PR to your tox.ini file: https://github.com/xlab-steampunk/workshops/pull/1 based on Paul's recommendation 

we were seeing this->
```
2021-05-28 16:43:37.590736 | centos-8 | |ERROR! Invalid collection name 'build/ansible-workshops-*.tar.gz', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.
2021-05-28 16:43:37.635249 | centos-8 | ERROR: InvocationError for command /home/zuul/src/github.com/ansible/workshops/.tox/workshop-f5/bin/ansible-galaxy collection install --verbose 'build/ansible-workshops-*.tar.gz' (exited with code 1)
```

**Comment by sstanovnik** [comment]
It may have something to do with the Ansible version being pinned to `<2.10`, I'll experiment starting with that - otherwise, I can just use a predictable name. I've been swamped these last few days but have managed to clear my backlog completely, so I'm back on this tomorrow!

**Comment by IPvSean** [comment]
Did you see my PR?

**Comment by sstanovnik** [comment]
I saw your PR but missed the change from `ansible` to `ansible-core`. I still had to make a slight modification to tox to get the wildcard to resolve, which seems to work fine with a replicated local CI setup. I'm waiting for the GitHub outage to pass so zuul starts picking up jobs again---at least I think that's what's wrong.

**Comment by sstanovnik** [comment]
Things are looking up. Here's what I'm facing right now. Mainly for me to distill the issues into a list so I don't have to consult the job outputs every time, but also if you do happen to have an immediate idea of why something is failing (or if it's normal), you can maybe solve it much quicker than I can.


## The `ansible.product_demos.install_demo` role is failing

Ref: search [this output](https://92d43800d11b5b7efced-0f4578393cd61b522470c72b553aaa73.ssl.cf5.rackcdn.com/1184/323ba0b213e0eab029ae2c22db432a7faae862f5/third-party-check/workshops-tox-integration-rhel/8bdd2da/job-output.txt) for `2021-06-02 12:10:39.765472 | centos-8 | TASK [ansible.product_demos.install_demo : install all job templates]`

I'm thinking this is an issue with the role and not the invocation. Passing/parsing [`full_demo_info` into a loop seems to fail](https://github.com/ansible/product-demos/blob/master/roles/install_demo/tasks/main.yml#L5), but `demo_info`, which is nearly identical, is just fine.


## AWS operations are throttled

Ref: search [this output](https://92d43800d11b5b7efced-0f4578393cd61b522470c72b553aaa73.ssl.cf5.rackcdn.com/1184/323ba0b213e0eab029ae2c22db432a7faae862f5/third-party-check/workshops-tox-integration-rhel/8bdd2da/job-output.txt) for `2021-06-02 12:15:19.922150`

Example:

```
2021-06-02 12:14:35.863242 | centos-8 | TASK [/home/zuul/src/github.com/ansible/workshops/provisioner/../roles/code_server : GRAB ROUTE53 INFORMATION] ***
2021-06-02 12:15:19.921909 | centos-8 | fatal: [localhost]: FAILED! => changed=false
2021-06-02 12:15:19.922150 | centos-8 |   msg: 'An error occurred (Throttling) when calling the ListResourceRecordSets operation (reached max retries: 4): '
```

If nothing else, I'll add retries to all such tasks, but this could get cumbersome.


## The CI image may be a bit outdated, TLS version error

This happens on every job, but is ignored. It's usually caused by the system not supporting TLS 1.2 or 1.3 or similar, and the remote not supporting anything lower that that.

Ref: search [this output](https://3340209948e3be29e367-024b07824a585b7b4291bc27eb6db0e5.ssl.cf5.rackcdn.com/1184/323ba0b213e0eab029ae2c22db432a7faae862f5/third-party-check/workshops-tox-integration-f5/ee3f82b/job-output.txt) for `2021-06-02 12:11:47.422891`

Example:

```
2021-06-02 12:11:47.422891 | centos-8 | TASK [/home/zuul/src/github.com/ansible/workshops/provisioner/../roles/issue_cert : change ansible tower base URL] ***
2021-06-02 12:11:51.355091 | centos-8 | FAILED - RETRYING: change ansible tower base URL (10 retries left).
2021-06-02 12:11:53.579437 | centos-8 | [WARNING]: You are using the awx version of this collection but connecting to
2021-06-02 12:11:53.579542 | centos-8 | Red Hat Ansible Tower
2021-06-02 12:11:53.579571 | centos-8 | changed: [tqe-gating-1184-cncddhcs-student1-ansible-1]
2021-06-02 12:11:59.867568 | centos-8 | FAILED - RETRYING: change ansible tower base URL (9 retries left).
2021-06-02 12:12:08.340170 | centos-8 | FAILED - RETRYING: change ansible tower base URL (8 retries left).
2021-06-02 12:12:16.786085 | centos-8 | FAILED - RETRYING: change ansible tower base URL (7 retries left).
2021-06-02 12:12:25.114537 | centos-8 | FAILED - RETRYING: change ansible tower base URL (6 retries left).
2021-06-02 12:12:33.441766 | centos-8 | FAILED - RETRYING: change ansible tower base URL (5 retries left).
2021-06-02 12:12:41.937812 | centos-8 | FAILED - RETRYING: change ansible tower base URL (4 retries left).
2021-06-02 12:12:50.393487 | centos-8 | FAILED - RETRYING: change ansible tower base URL (3 retries left).
2021-06-02 12:12:58.729939 | centos-8 | FAILED - RETRYING: change ansible tower base URL (2 retries left).
2021-06-02 12:13:07.171610 | centos-8 | FAILED - RETRYING: change ansible tower base URL (1 retries left).
2021-06-02 12:13:15.639909 | centos-8 | fatal: [tqe-gating-1184-cncddhcs-student2-ansible-1]: FAILED! => changed=false
2021-06-02 12:13:15.640103 | centos-8 |   attempts: 10
2021-06-02 12:13:15.640128 | centos-8 |   msg: 'Failed to get token: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)>'
```


## `network os eos is not supported`

Deprecation in collection maybe? Will investigate.

Ref: search [this output](https://234e9f58110c321bb98f-24f07c62a65a748a8df26f69b2c66846.ssl.cf2.rackcdn.com/1184/323ba0b213e0eab029ae2c22db432a7faae862f5/third-party-check/workshops-tox-integration-networking/9684d4c/job-output.txt) for `2021-06-02 12:11:09.120572`

Example

```
2021-06-02 12:11:09.120572 | centos-8 | TASK [/home/zuul/src/github.com/ansible/workshops/provisioner/../roles/configure_routers : apply network device template] ***
2021-06-02 12:11:09.368038 | centos-8 | fatal: [tqe-gating-1184-uiswzirj-student1-rtr4]: FAILED! =>
2021-06-02 12:11:09.368076 | centos-8 |   msg: network os eos is not supported
2021-06-02 12:11:09.399470 | centos-8 | fatal: [tqe-gating-1184-uiswzirj-student2-rtr4]: FAILED! =>
2021-06-02 12:11:09.399508 | centos-8 |   msg: network os eos is not supported
2021-06-02 12:11:18.489245 | centos-8 | [WARNING]: To ensure idempotency and correct diff the input configuration lines
2021-06-02 12:11:18.489280 | centos-8 | should be similar to how they appear if present in the running configuration on
2021-06-02 12:11:18.489286 | centos-8 | device including the indentation
2021-06-02 12:11:18.489292 | centos-8 | changed: [tqe-gating-1184-uiswzirj-student1-rtr3]
2021-06-02 12:11:18.530726 | centos-8 | changed: [tqe-gating-1184-uiswzirj-student2-rtr3]
```

## NoneType is not iterable in verification

Could maybe be caused because we're using awx.awx against Tower? There's a warning for this somewhere.

Ref: search [this output](https://0138d315b836cfa52530-9a7b50ef6dbe08e70b4b461091c56792.ssl.cf1.rackcdn.com/1184/323ba0b213e0eab029ae2c22db432a7faae862f5/third-party-check/workshops-tox-integration-smart-mgmt/b207d61/job-output.txt) for `2021-06-02 12:11:45.253283`

Example:

```
2021-06-02 12:11:45.253283 | centos-8 | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object is not iterable
2021-06-02 12:11:45.264006 | centos-8 | fatal: [student2-ansible-1]: FAILED! => changed=false
2021-06-02 12:11:45.264047 | centos-8 |   attempts: 60
2021-06-02 12:11:45.264078 | centos-8 |   module_stderr: |-
2021-06-02 12:11:45.264098 | centos-8 |     Shared connection to 54.243.26.227 closed.
2021-06-02 12:11:45.264125 | centos-8 |   module_stdout: |-
2021-06-02 12:11:45.264150 | centos-8 |     Traceback (most recent call last):
2021-06-02 12:11:45.264170 | centos-8 |       File "/home/ec2-user/.ansible/tmp/ansible-tmp-1622635904.4628747-31491-942402557157/AnsiballZ_tower_receive.py", line 100, in <module>
2021-06-02 12:11:45.264183 | centos-8 |         _ansiballz_main()
2021-06-02 12:11:45.264196 | centos-8 |       File "/home/ec2-user/.ansible/tmp/ansible-tmp-1622635904.4628747-31491-942402557157/AnsiballZ_tower_receive.py", line 92, in _ansiballz_main
2021-06-02 12:11:45.264230 | centos-8 |         invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
2021-06-02 12:11:45.264258 | centos-8 |       File "/home/ec2-user/.ansible/tmp/ansible-tmp-1622635904.4628747-31491-942402557157/AnsiballZ_tower_receive.py", line 41, in invoke_module
2021-06-02 12:11:45.264275 | centos-8 |         run_name='__main__', alter_sys=True)
2021-06-02 12:11:45.264288 | centos-8 |       File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
2021-06-02 12:11:45.264318 | centos-8 |         return _run_module_code(code, init_globals, run_name, mod_spec)
2021-06-02 12:11:45.264333 | centos-8 |       File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
2021-06-02 12:11:45.264346 | centos-8 |         mod_name, mod_spec, pkg_name, script_name)
2021-06-02 12:11:45.264358 | centos-8 |       File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
2021-06-02 12:11:45.264370 | centos-8 |         exec(code, run_globals)
2021-06-02 12:11:45.264411 | centos-8 |       File "/tmp/ansible_tower_receive_payload_chiol8c7/ansible_tower_receive_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_receive.py", line 192, in <module>
2021-06-02 12:11:45.264466 | centos-8 |       File "/tmp/ansible_tower_receive_payload_chiol8c7/ansible_tower_receive_payload.zip/ansible_collections/awx/awx/plugins/modules/tower_receive.py", line 184, in main
2021-06-02 12:11:45.264495 | centos-8 |       File "/usr/local/lib/python3.6/site-packages/tower_cli/cli/transfer/receive.py", line 27, in export_assets
2021-06-02 12:11:45.264514 | centos-8 |         assets_to_export = common.get_assets_from_input(all, asset_input)
2021-06-02 12:11:45.264527 | centos-8 |       File "/usr/local/lib/python3.6/site-packages/tower_cli/cli/transfer/common.py", line 413, in get_assets_from_input
2021-06-02 12:11:45.264539 | centos-8 |         for asset_name in asset_input[asset_type]:
2021-06-02 12:11:45.264551 | centos-8 |     TypeError: 'NoneType' object is not iterable
2021-06-02 12:11:45.264563 | centos-8 |   msg: |-
2021-06-02 12:11:45.264575 | centos-8 |     MODULE FAILURE
2021-06-02 12:11:45.264587 | centos-8 |     See stdout/stderr for the exact error
2021-06-02 12:11:45.264599 | centos-8 |   rc: 1
```

## Skipping callback plugin `time` (not fatal)

Will need to check historical runs to see if this is present. `time` does not exist as a callback plugin - there's only `ansible.posix.timer`. Not a blocker anyway.

Example: 

```
[WARNING]: Skipping callback plugin 'time', unable to load
```


## The Tower license is expired (not fatal)

Is this expected? Will consult historic runs.

```
2021-06-02 11:41:39.357500 | centos-8 | TASK [/home/zuul/src/github.com/ansible/workshops/provisioner/../roles/workshop_check_setup : Ensure tower license is not expired] ***
2021-06-02 11:41:39.431655 | centos-8 | fatal: [localhost]: FAILED! => changed=false
2021-06-02 11:41:39.431748 | centos-8 |   assertion: ansible_date_time.epoch|int < tower_license.license_date|int
2021-06-02 11:41:39.431768 | centos-8 |   evaluated_to: false
2021-06-02 11:41:39.431799 | centos-8 |   msg: 'WARNING: Ansible Tower License expired.'
2021-06-02 11:41:39.431925 | centos-8 | ...ignoring
```

**Comment by sstanovnik** [comment]
@IPvSean I'd like to borrow your eyes on the above three issues that are left in the previous comment if you get the chance. It's very likely you can grok things faster than I can decompile them, especially number 3.

My notes to continue with tomorrow:

1. This is just a syntax thing I think, but I'll need to parse out the intention behind the variable to see where things go wrong.
2. Not really sure why AWS operations weren't throttled before, since execution is basically identical. Maybe due to an `{community,amazon}.aws` upgrade. If nothing else, I'll try adding some retries or use the `aws_config` variable to configure retries in case of throttling.
3. A bit clueless as to what's happening here. The root cause isn't TLS at all. Here are two outputs from a different task that provide some insight into the issue.

#### Working run (from a previous PR)

```
TASK [control_node : Display /api/v2/ping results] *****************************
ok: [tqe-gating-1186-extodghn-student1-ansible-1] =>
  msg:
    active_node: localhost
    ha: false
    install_uuid: 5fba5dda-0fe8-4dcb-838b-67b2589b4e06
    instance_groups:
    - capacity: 16
      instances:
      - localhost
      name: tower
    instances:
    - capacity: 16
      heartbeat: '2021-06-01T15:42:04.482077Z'
      node: localhost
      uuid: a9eb363d-a5d5-417d-ae87-eda1eac663c4
      version: 3.7.3
    version: 3.7.3
ok: [tqe-gating-1186-extodghn-student2-ansible-1] =>
  msg:
    active_node: localhost
    ha: false
    install_uuid: f336c3aa-e1af-44f9-9122-050d82ff3066
    instance_groups:
    - capacity: 16
      instances:
      - localhost
      name: tower
    instances:
    - capacity: 16
      heartbeat: '2021-06-01T15:42:31.847705Z'
      node: localhost
      uuid: b788cca9-1cf7-4793-bfc4-77d13573d662
      version: 3.7.3
    version: 3.7.3
```

#### Failing run (this PR)

```
TASK [/home/zuul/src/github.com/ansible/workshops/provisioner/../roles/control_node : Display /api/v2/ping results] ***
ok: [tqe-gating-1184-cncddhcs-student1-ansible-1] =>
  msg:
    active_node: localhost
    ha: false
    install_uuid: 2be87285-a601-4e9e-a4e6-720aa7d7ca75
    instance_groups:
    - capacity: 16
      instances:
      - localhost
      name: tower
    instances:
    - capacity: 16
      heartbeat: '2021-06-02T12:06:54.435536Z'
      node: localhost
      uuid: 6a65d2ec-9633-466c-a7bb-134e7e06f60e
      version: 3.7.3
    version: 3.7.3
ok: [tqe-gating-1184-cncddhcs-student2-ansible-1] =>
  msg:
    active_node: localhost
    ha: false
    install_uuid: 7d7ced20-6a27-412d-8130-0783734b1595
    instance_groups:
    - capacity: 0   <<<===============================================================================
      instances:
      - localhost
      name: tower
    instances:
    - capacity: 0   <<<===============================================================================
      heartbeat: '2021-06-02T12:05:11.454286Z'
      node: localhost
      uuid: d5611026-b25e-4d59-bfa6-38b3c2db7633
      version: ''
    version: 3.7.3
```

I'm not familiar with Tower except for very basic usage of AWS. What is "capacity"? How can it be 0 for one of the two identical machines? This doesn't happen consistently. Do we just need to wait for some background jobs to finish? Maybe a known intermittent issue? Note to self, maybe try waiting 10 minutes until both capacities are >0 here.

**Comment by IPvSean** [comment]
hey @sstanovnik investigating now, sorry Wednesday are still super tough in North Carolina with school shutdowns.

**Comment by sstanovnik** [comment]
No worries. For the issue with product_demos, I'm stuck on what seems to be an Ansible/Python combo bug. Ansible 2.9 + Python 3.6, which we had before, worked, but anything `ansible-{base,core}>=2.10.0` will not work with `python>3.6,<3.7`. It's got to do with `vars` sometimes being a string for some reason. The most proper fix is using a newer version of Python, I think, since Ansible 2.12 will drop support for 3.6, but that means modifying the system. Thoughts?

The throttling task retries didn't work, but I'll set them to a larger delay than 30 seconds and see if that helps.

I also saw another error with `NoneType is not iterable`, which I was sure I fixed, so I need to investigate this further.

**Comment by IPvSean** [comment]
I feel like.... I need to reinvestigate the product demos this morning.... that is meant to be a collection to install a Job template (a unit of automation) on Ansible Tower (soon to be called Automation Controller which you might see in the Readme.MD). 

 A job template is simply a project (which points to a playbook) + a credential (to login to the thing we are automating) + inventory (what we are automating against).  Think of tower as just operationalizing playbooks for a team....

IMHO... I probably could simplify the product demos significantly... b/c even in steady-state it was giving off a ton of warnings b/c of some odd trickery I dod with variable loading.


with the AWS rate limit.... I am investigating that with our engineers...  I have seen that problem pop up before but never in CI... usually it is when we are creating huge 50-> 100 person labs....  this might be opportunity to move to newer modules that are all running on boto3....

**Comment by sstanovnik** [comment]
I'll make a PR changing variable handling to avoid using `vars` if that's okay with you. I'll test in this CI by installing the collection directly from the repository so we get a working release.

The only modules I see causing timeouts are `route53*`, which still use `boto`, not `boto3`. Do newer ones for Route53 exist?

**Comment by IPvSean** [comment]
> I'll make a PR changing variable handling to avoid using `vars` if that's okay with you. I'll test in this CI by installing the collection directly from the repository so we get a working release.
> 
> The only modules I see causing timeouts are `route53*`, which still use `boto`, not `boto3`. Do newer ones for Route53 exist?

this was accepted upstream into github.com/ansible/product-demos, I will look at the next few

**Comment by IPvSean** [comment]
OK let me try to summarize for my own sanity->

- workshops-tox-integration-f5 : FAILURE in 57m 49s

failing because of the product demos, this is now fixed upstream

- workshops-tox-integration-networking : FAILURE in 1h 11m 34s

```
```
TASK [/home/zuul/src/github.com/ansible/workshops/provisioner/../roles/workshop_attendance : GRAB ROUTE53 INFORMATION] ***
FAILED - RETRYING: GRAB ROUTE53 INFORMATION (5 retries left).
FAILED - RETRYING: GRAB ROUTE53 INFORMATION (4 retries left).
FAILED - RETRYING: GRAB ROUTE53 INFORMATION (3 retries left).
FAILED - RETRYING: GRAB ROUTE53 INFORMATION (2 retries left).
FAILED - RETRYING: GRAB ROUTE53 INFORMATION (1 retries left).
fatal: [localhost]: FAILED! => changed=false 
  attempts: 5
  msg: 'An error occurred (Throttling) when calling the ListResourceRecordSets operation (reached max retries: 4): '
```

this is this task:
```
- name: GRAB ROUTE53 INFORMATION
  route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{AWSINFO.zone_id}}"
    start_record_name: "student1.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
  register: record_sets
```

I agree with your comment above->

add something like
```
- name: GRAB ROUTE53 INFORMATION
  route53_info:
    aws_config:
      retries:
        max_attempts: 10
```

I think that will help



- workshops-tox-integration-rhel : FAILURE in 55m 19s

```
TASK [/home/zuul/src/github.com/ansible/workshops/provisioner/../roles/issue_cert : change ansible tower base URL] ***
FAILED - RETRYING: change ansible tower base URL (10 retries left).
[WARNING]: You are using the awx version of this collection but connecting to
Red Hat Ansible Tower
changed: [tqe-gating-1184-tpezbqsk-student2-ansible-1]
FAILED - RETRYING: change ansible tower base URL (9 retries left).
FAILED - RETRYING: change ansible tower base URL (8 retries left).
FAILED - RETRYING: change ansible tower base URL (7 retries left).
FAILED - RETRYING: change ansible tower base URL (6 retries left).
FAILED - RETRYING: change ansible tower base URL (5 retries left).
FAILED - RETRYING: change ansible tower base URL (4 retries left).
FAILED - RETRYING: change ansible tower base URL (3 retries left).
FAILED - RETRYING: change ansible tower base URL (2 retries left).
FAILED - RETRYING: change ansible tower base URL (1 retries left).
fatal: [tqe-gating-1184-tpezbqsk-student1-ansible-1]: FAILED! => changed=false 
  attempts: 10
  msg: 'Failed to get token: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:897)>'
```

I think this is your comment on this->

> A bit clueless as to what's happening here. The root cause isn't TLS at all. Here are two outputs from a different task that provide some insight into the issue.


This one I thought I fixed.... it makes zero sense to me as well....  I will reach out to engineering to see if they know any other tricks....

this task is actually already converted to roles before you started working on it->

`roles/issue_cert/tasks/main.yml`

```
    - name: change ansible tower base URL
      awx.awx.tower_settings:
        name: TOWER_URL_BASE
        value: "https://{{ dns_name }}"
        tower_verify_ssl: false
        tower_host: localhost
        tower_username: admin
        tower_password: "{{ admin_password }}"
      register: change_base_url
      until: change_base_url is not failed
      retries: 10
```

glad this one threw you as well... I can only assume Ansible Tower (our WebUI/APi for Ansible) is not up and running yet.... it is very bizarre that it sometimes disappears and comes bakc


- workshops-tox-integration-security : FAILURE in 1h 11m 10s

this is failing the same as networking b/c of aws... so hopefully the teardown fix will work for this as well

- workshops-tox-integration-smart-mgmt : FAILURE in 1h 29m 48s

will circle back on this tomorrow

- workshops-tox-integration-windows : FAILURE in 1h 09m 51s

this one is another route53 issue, however this one is stored at `provisioner/roles/gitlab-server/tasks/teardown.yml`

so can you add that there as well?

**Comment by IPvSean** [comment]
recheck

**Comment by sstanovnik** [comment]
I've made a huge leap in progress! The changes to `product_demos` weren't taking effect because `workshop_check_setup` was force-installing the latest version from Galaxy at runtime. Some issues remain but this is a good step forward.

**Comment by IPvSean** [comment]
@sstanovnik ah good point, doing a new release of product demos to galaxy

```
➜  product-demos git:(master) ✗ ansible-galaxy collection publish /Users/sean/Documents/GitHub/IPvSean/product-demos/ansible-product_demos-1.2.6.tar.gz
Publishing collection artifact '/Users/sean/Documents/GitHub/IPvSean/product-demos/ansible-product_demos-1.2.6.tar.gz' to release_galaxy https://galaxy.ansible.com/api/
Collection has been published to the Galaxy server release_galaxy https://galaxy.ansible.com/api/
Waiting until Galaxy import task https://galaxy.ansible.com/api/v2/collection-imports/11293/ has completed
Collection has been successfully published and imported to the Galaxy server release_galaxy https://galaxy.ansible.com/api/
```

**Comment by sstanovnik** [comment]
I think that release product-demos has a bug (which I caused, sorry about this, and the extra parentheses) @IPvSean, see my fix at https://github.com/xlab-steampunk/product-demos/commit/95b02723cc2f86abba106f9467ea2044502f5f64. I'm testing it here and it seems to work.

Good news: I got `security` to work! Other workshops fail with AWS throttling or Tower whatever-it-is.

For throttling, I've added botocore-level retries with adaptive backoff, which don't seem to help. I've increased the number of tries to see if that helps.

For the Tower issue, I've resorted to trying to restart the thing if it fails. It may help, since waiting obviously doesn't.

What worries me is that we now have a CI timeout for `rhel` due to us waiting for AWS throttling.

**Comment by IPvSean** [comment]
> I think that release product-demos has a bug (which I caused, sorry about this, and the extra parentheses) @IPvSean

it did, but I fixed it on my end :) Easy to fix.

>  see my fix at xlab-steampunk/product-demos@95b0272. I'm testing it here and it seems to work.
this looks different from the parentheses, but I pushed this to master

also pushed the release to galaxy
```
➜  product-demos git:(master) ✗ ansible-galaxy collection publish /Users/sean/Documents/GitHub/IPvSean/product-demos/ansible-product_demos-1.2.7.tar.gz
Publishing collection artifact '/Users/sean/Documents/GitHub/IPvSean/product-demos/ansible-product_demos-1.2.7.tar.gz' to release_galaxy https://galaxy.ansible.com/api/
Collection has been published to the Galaxy server release_galaxy https://galaxy.ansible.com/api/
Waiting until Galaxy import task https://galaxy.ansible.com/api/v2/collection-imports/11298/ has completed
Collection has been successfully published and imported to the Galaxy server release_galaxy https://galaxy.ansible.com/api/
```

> For throttling, I've added botocore-level retries with adaptive backoff, which don't seem to help. I've increased the number of tries to see if that helps.

let me investigate... might be time to have @jillr look at it

> For the Tower issue, I've resorted to trying to restart the thing if it fails. It may help, since waiting obviously doesn't.

i thought I fixed this....

this is what the infamous @chrismeyers had said->
image

**Comment by sstanovnik** [comment]
After many tribulations, I've finally managed to get things working!

Tower is still failing sometimes. It's being ignored as is intended (there's a rescue block that ignores failures there), but I don't know if that's okay, since the intermittent unreliability can be annoying. I've added more debug output to hopefully show where the error is in more detail.

As for the AWS throttling error, this is also solved. However, this required monkeypatching `community.aws.route53_info`, which is a bit ugly, but the only solution that worked.

I think the main issue is that Route53 [has an account-wide 5 req/s limit](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests). Waiting a significant amount of time, randomly (so evenly distributed between concurrent jobs), didn't help. Ansible retries didn't help. Boto-level retries with exponential backoff, either "standard" or "adaptive", didn't help.

Since `route53_info` was the only module that was failing and things were okay before this PR, I managed to narrow down the problem by comparing the code of the module from `ansible<2.10` and `community.aws`. The only difference was that the module now uses paginators instead of the bare boto client. I've `sed`-ed it to the previous behaviour and things started working. This may or may not mean that the module doesn't respect `max_items: 1` and fetches all data, but I didn't jump into that rabbit hole.

Anyway, this is now RFR, @IPvSean!

**Comment by sstanovnik** [comment]
I've just noticed that I've accidentaly rebased onto master instead of devel. I'll let the current CI run finish and then rebase back onto devel.

**Pull request merged**
