### PR TITLE
Reverse the template order in the workflow exercise

### LINKED ISSUE #1381: Ansible Linux Workshop Exercise 2.6 Workflows
When creating the workflow, the suggestion is to put the "Node.js deploy"-template first and the "Web App Deploy"-template second. This results in a failure, if you switch them around it works.

### PR DESCRIPTION
**Pull request by dpullman-emergent**
##### SUMMARY

Fixes #1381 

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

- exercises

##### ADDITIONAL INFORMATION

Changed the exercise to reverse the template order so the workflow will completd.

Under "Lab scenario":
- Elaborate a bit about what changes are needed by each team.
- Add a line that summarises the changes.

Under "Set up the workflow":
- Change the order of the start graphic and the instruction.
- Change the first template to be Web App Deploy.
- Change the graphic from add_node_nodejs to add_node.
- Edit to the text leading to the second template.
- Move tip for type after the step to select run type.
- Change the second template to be Node.js Deploy.
- Change the graphic from add_node to add_node_nodejs.

Under "Launch workflow":
- Change the instruction to run from control node to all three nodes.
- Change the bash example.
- Remove redundant final instruction.

Replace images for workflow_node and job_workflow to match new order.

```paste below

```

### CODE REVIEW

**Comment by rlopez133** [comment]
@IPvSean LGTM

**Comment by HarmtH** [comment]
I would just change the names of the templates, seems more logical:
```diff
diff --git a/exercises/ansible_rhel/2.6-workflows/README.md b/exercises/ansible_rhel/2.6-workflows/README.md
index 0fc16751..d1a74b14 100644
--- a/exercises/ansible_rhel/2.6-workflows/README.md
+++ b/exercises/ansible_rhel/2.6-workflows/README.md
@@ -153,7 +153,7 @@ Within **Resources** -> **Templates**, click the **Add** button and choose **Add
     </tr>
     <tr>
       <td>Name</td>
-      <td>Web App Deploy</td>
+      <td>Node.js Deploy</td>
     </tr>
     <tr>
       <td>Job Type</td>
@@ -202,7 +202,7 @@ Within **Resources** -> **Templates**, click the **Add** button and choose **Add
     </tr>
     <tr>
       <td>Name</td>
-      <td>Node.js Deploy</td>
+      <td>Web App Deploy</td>
     </tr>
     <tr>
       <td>Job Type</td>
```

**Comment by dpullman-emergent** [comment]
@HarmtH , I'm not sure that would correct the failure of the workflow to complete? It was failing because systemctl did not have a service to work with in the original order.

Also, the graphics need to show the order change so it makes sense? 

Those two things are trying to make the workflow run correctly. The other changes are just my attempt to make the description a little clearer as to what is happening :)

**Comment by HarmtH** [comment]
@dpullman-emergent If you only swap the names, the 'Node.js Deploy' template points to the webops branch, and the 'Web App Deploy' template points to the webdev branch. That makes the rest of the documentation, and the images, correct, right?

**Comment by dpullman-emergent** [comment]
Well, I thought the approach I was doing was good so that the underlying parts would make sense, and so that the exercise was a little easier to understand for attendees with less experience. I'm happy to leave the decision about this to the maintainers :)

**Comment by rlopez133** [comment]
I went ahead and deployed a workshop and tested what @dpullman-emergent created and it works as expected. I'm ok with merging as is.

**Pull request merged**
