### PR TITLE
os_config means generic name *os_config

### PR DESCRIPTION
**Pull request by sugitk**
##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

- exercises

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by sugitk** [comment]
translated #738

**Comment by Spredzy** [comment]
recheck

**Comment by IPvSean** [comment]
@htaira does this look good to you?

**Comment by htaira** [comment]
@IPvSean LGTM

**Pull request merged**
