### PR TITLE
AWS API access via Tower IAM instance role - Smart Management workshop

### PR DESCRIPTION
**Pull request by heatmiser**
##### SUMMARY
The new Smart Management workshop has a Convert2RHEL exercise where it would be beneficial to allow participants to create snapshots of instances, revert instances from snapshots, as well as provide the ability to stop, start, and restart instances and modify EC2 instance tags throughout the exercise via the AWS API.  In order to provide this ability to participants, an AWS IAM policy is assigned to a role/instance profile that, in turn, is attached to the student Tower node.  Job templates in Tower pass AWS API access authorization through via the boto library and AWS API capabilities are limited via the IAM policy provided.  Additionally, each non-Tower node has a role/instance profile attached, which is tied to the Tower-specific role/instance profile, thus ensuring the provided AWS API capabilities are contained/limited to each participant's provisioned workshop nodes.

In addition to the earlier mentioned capabilities, the above configuration provides a means to implement dynamic inventories in workshop exercises.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
In order to turn on the above capabilities for a Smart Management workshop deployment, include the following in the smart managment workshop config vars file:
```
tower_node_aws_api_access: true
```

### CODE REVIEW

**Comment by heatmiser** [comment]
Zuul failure in provisioner/roles/manage_ec2_instances/tasks/teardown.yml  ==>  429:15    warning  truthy value should be one of [false, true]  (truthy)
Line in question (429:15)
`wait: yes`
[Ansible source code](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/parsing/convert_bool.py) indicates that `yes` is acceptable as a BOOLEANS_TRUE value. And performing a search on `yes no` in the ansible github repo shows that the integration tests primarily use `yes` or `no`

**Comment by heatmiser** [comment]
The following is a description of the mechanics of the IAM policy utilized for this implementation and is based on the following AWS security blog, posted by Chris Craig on Sep 22, 2015: https://aws.amazon.com/blogs/security/how-to-help-lock-down-a-users-amazon-ec2-capabilities-to-a-single-vpc/

The Tower instance node has an AWS IAM role tied to it via an IAM instance profile, based on the policy template `provisioner/roles/manage_ec2_instances/templates/iam_vpc_lockdown_policy.json.j2` and is named in the following manner: `ControlNode_<workshop-name>_<student-name>`, for example: `ControlNode_smrtmgmt01_student23`

Each non-Tower node that is to be automated/controlled by the Tower instance also has an AWS IAM role tied to it via an IAM instance profile, however this policy is a much simpler "pass-through" policy and is based on the policy template `provisioner/roles/manage_ec2_instances/files/AssumeRole_policy.json` and named in the following manner: `VPCLockDown_<workshop-name>_<student-name>`, for example: `VPCLockDown_smrtmgmt01_student23`. The Lockdown role is utilized throughout the above Tower instance IAM policy, essentially locking down what nodes the Tower instance can act upon.

The following is a summary, speaking to individual "Sid" sections within the `iam_vpc_lockdown_policy.json.j2` template mentioned earlier.

"Sid": "AllowInstanceActions"
- Actions/resources related to starting and stopping instances, plus taking snapshots. Requires instances being acted upon have associated "Lockdown" instance profile/role.

"Sid": "EC2RunInstances"
- Action related to running instances. Requires instances being acted upon have associated "Lockdown" instance profile/role.

"Sid": "EC2RunInstancesSubnet"
- Action/resources related to networking aspects of running an instance within a VPC and is tied to the specific workshop VPC utilized.

"Sid": "RemainingRunInstancePermissions"
- Other miscellaneous running instance resources permissions, tied to objects tagged with the specific student name, ie. student23

"Sid": "EC2CreateSnapshot"
- Allow creating snapshots within the account. This feature is used in the convert2rhel exercise portion of the Smart Management workshop. However, this feature could be extended to other workshops; providing a means for students to create a "pre-exercises" copy of the nodes in their specific workshop deployment and allowing students to "reset" the lab to square one, starting exercises over to attempt alternate automation steps if so desired.

"Sid": "Route53Actions"
- Allow the update of DNS records that are part of the workshop domain.  This provides a means to shut the entire workshop down and then restart at a later time. Stopping and starting EC2 instances means the instances have new external IP address when started again, thus breaking DNS resolution with the associated records in Route53. This capability permits the introduction of automation to update workshop Route53 DNS records when the workshop instances are started after being in the stopped state.

"Sid": "NonResourceBasedReadOnlyPermissions"
- Read-only allow actions.

"Sid": "IAMPassroleToInstance"
- IAM PassRole of the VPCLockDown IAM role, providing the mechanism for tying into the "pass through" lockdown role.

"Sid": "AttachAndDetachVolume"
- Provide means for attaching and detaching volumes, utilized in the convert2rhel exercise portion of the Smart Management workshop. For those occasions of a failed convert2rhel process, the student can revert back to pre-conversion node state.

**Comment by heatmiser** [comment]
Please consider accepting [PR#1153](https://github.com/ansible/workshops/pull/1153) which would resolve the Zuul failure in `provisioner/roles/manage_ec2_instances/tasks/teardown.yml` ==> `429:15 warning truthy value should be one of [false, true] (truthy)`

**Comment by heatmiser** [comment]
After @Spredzy comments on [PR#1153](https://github.com/ansible/workshops/pull/1153) and it's subsequent closing, I will make the requisite adjustments shortly, then commit and push.

**Comment by heatmiser** [comment]
@IPvSean This appears to be failing during the clustered control nodes use case, which is one that @willtome and I had discussed as not being a supported use case for the `smart_mgmt` workshop.  However, if this is a scenario that needs to be supported in case other workshops would like to be configured to utilize IAM instance roles for integrated AWS API access in the future, then please advise on one of the following two scenarios:
1)  I work to rectify the issue now, however, this will further delay getting the functionality into `smart_mgmt` workshops
2) Can we run the zuul tests to only utilize a single control node deployment for this particular PR?  And if so, upon passing the tests, accept the PR as-is and I will work on a follow-up PR to include support for clustered control node workshop use cases?

**Comment by willtome** [comment]
I don't see a need for clustered Tower nodes in this workshop. It should not be a blocker to move forward. Adding it later can always be an option if we find a need for it down the road.

**Comment by IPvSean** [comment]
I am not sure I understand, the error that is fatal is this->
```
TASK [manage_ec2_instances : Associate IAM instance profile with control node] ***
fatal: [localhost]: FAILED! => 
  msg: 'The conditional check ''"There is an existing association for instance" not in associate_iam_instance_profile.stderr'' failed. The error was: error while evaluating conditional ("There is an existing association for instance" not in associate_iam_instance_profile.stderr): ''dict object'' has no attribute ''stderr'''
```

I am not sure what that has to do with the cluster?

I also can't seem to find that code when I look through your repo->
https://github.com/heatmiser/workshops/search?q=Associate+IAM&type=code

**Comment by heatmiser** [comment]
@IPvSean the `Associate IAM instance profile with control node` task starts [here](https://github.com/heatmiser/workshops/blob/5df904dcd3e79e0d5d2c3feed03155a000a18e14/provisioner/roles/manage_ec2_instances/tasks/cluster_instances.yml#L82).

Looking in the zuul logs for: workshops-tox-integration-smart-mgmt : FAILURE in 12m 33s

```TASK [manage_ec2_instances : Create the control clusters] **********************
included: /home/zuul/src/github.com/ansible/workshops/provisioner/roles/manage_ec2_instances/tasks/cluster_instances.yml for localhost

TASK [manage_ec2_instances : Create EC2 instances for ansible node (control node)] ***
changed: [localhost]

TASK [manage_ec2_instances : Ensure tags are present] **************************
changed: [localhost] => (item=[0, {'id': 'i-014e4918b5f8b70ba', 'ami_launch_index': '0', ...)
changed: [localhost] => (item=[1, {'id': 'i-0f57461ca4f9befe3', 'ami_launch_index': '1', ...)

TASK [manage_ec2_instances : GRAB ROUTE53 ZONE ID] *****************************
ok: [localhost]

TASK [manage_ec2_instances : Create VPC Lock Down role] ************************
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)

TASK [manage_ec2_instances : Create control node instance role] ****************
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)

TASK [manage_ec2_instances : Generate IAM policy for control node IAM instance role] ***
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)

TASK [manage_ec2_instances : Associate IAM instance profile with control node] ***
fatal: [localhost]: FAILED! =>
msg: 'The conditional check ''"There is an existing association for instance" not in associate_iam_instance_profile.stderr'' failed. The error was: error while evaluating conditional ("There is an existing association for instance" not in associate_iam_instance_profile.stderr): ''dict object'' has no attribute ''stderr'''

PLAY RECAP *********************************************************************
localhost                  : ok=53   changed=20   unreachable=0    failed=1    skipped=11   rescued=0    ignored=1
```

Notice that there are two items, which I'm assuming means the test is deploying clustered control nodes?  I did not account for the possibility for multiple control nodes in my code, I never tried this scenario in my dev and testing deployments, so I'm assuming this is why the error is occurring.  I do not see this issue in my local deployments using a single control node and I'm deploying with this code base weekly, sometimes daily, for my personal demos.

**Comment by willtome** [comment]
I can't reproduce this error. Is it possible to get more logs or details on how this is running? In these CI runs, is the updated test file that is part of this PR used? @Spredzy can you help us out with this? Thanks

**Pull request merged**
