### PR TITLE
Move instance tags

### PR DESCRIPTION
**Pull request by cigamit**
##### SUMMARY
There is a failure in the way that we are doing count_tag vs instance_tag.  We don't apply an instance_tag with the same name as the count_tag during creation, if the ec2_tag fails, the instance is not properly tagged with what we are using for the count_tag and thus will not be "counted" if provisioning has to be reran, or during aws calls to collect instance information.   This becomes more readily apparent if the failure happens and we move to a dynamic inventory script (luckily our add_hosts saves us for now).  This is easily fixed by adding the count_tag via an instance_tag during creation instead of later.

This PR adds the count_tag during creation, but it also moves all non-unique tags to creation time (there is no benefit to having them added later).  Only tags that are unique per individual host are left in the ec2_tag call.  If the ec2_tag call fails for any reason (rate limiting), we now have much more information about the VM to allow us to decide on whether it should be cleaned up or not.

A few of our workshops had inconsistent tagging across nodes (some didn't have launch time, etc..) and I also added a few more tags to our resources.  Specifically adding the workshop_type to the VPC is going to be a huge help in cleaning up stale VMs.

I also do a bit of formatting cleanup of variables to make them easier to read within these files.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION
I may attempt to remove all common tags into their own array and include them in via a variable.  This would help eliminate a bit of code and ensure tags stay consistent across all VMs.  I also wouldn't mind removing the unique per node tag for example
`       Workshop_rtr1: "{{ ec2_name_prefix }}-rtr1"`
and move to a more generic key (maybe "Workshop_Instance_Type") that will make it easier to work with, but will have to verify all places in the code that we use these types of tags.

I would also like to move the launch time from dynamic variable pulled from the host, to the time that we issued the create command and include it in at creation time versus later via tagging.

### CODE REVIEW

**Comment by cigamit** [comment]
Seems I need to fix the launch_time tag in the F5 workshop.  I will update it tonight.

**Comment by IPvSean** [comment]
>There is a failure in the way that we are doing count_tag vs instance_tag. We don't apply an instance_tag with the same name as the count_tag during creation, if the ec2_tag fails, the instance is not properly tagged with what we are using for the count_tag and thus will not be "counted" if provisioning has to be reran

I am pretty sure the count_tag also tags, I had run this by Ryan Brown before he left Red Hat.  I am not sure what would happen if you do both types of tags with the same name, probably nothing as long as they match.

**Comment by cigamit** [comment]
I did tests before creating this PR.  You can also, just make it fail after it creates the vm.  count_tag does not tag it itself, you have to put it under instance_tags for it actually tag the VM.

**Comment by IPvSean** [comment]
Recheck

**Comment by IPvSean** [comment]
passing ci

**Pull request merged**
