### PR TITLE
Adding Windows workflow chapter at top level

### PR DESCRIPTION
**Pull request by anshulbehl**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME

- exercises
- docs
- decks
- provisioner
- demos

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by anshulbehl** [comment]
recheck

**Comment by IPvSean** [comment]
recheck

**Comment by IPvSean** [comment]
wow i can't win on CI...

**Comment by IPvSean** [comment]
recheck

**Pull request merged**
