### PR TITLE
Creates login page for all workshop types

### PR DESCRIPTION
**Pull request by cloin**
##### SUMMARY

`attendance: true` creates a new instance to host a db and website for users to pull student numbers for a workshop

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- provisioner

### CODE REVIEW

**Comment by cloin** [comment]
@liquidat @IPvSean this is pretty close. Few fixes I need to make and I will probably concat the two attendance roles. 

Provisioning a workshop with `attendace: true` should create a page at `login.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}` 

`login.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/list.php` secured by `{{ admin_password }}` contains a list of user info and student workbench assignment

**Comment by IPvSean** [comment]
can you rebase @cloin

**Comment by IPvSean** [comment]
can you rebase @cloin

**Comment by cloin** [comment]
Ah shit. Burn it down.

**Pull request closed without merging**
