### PR TITLE
fix typo(Managed Host 2 -> Managed Host 3)

### PR DESCRIPTION
**Pull request by taro-hida**
##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request

##### COMPONENT NAME

- exercises
- docs
- decks
- provisioner
- demos

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
@taro-hida could you re open this PR against the `devel` branch please (currently opened against the `master` branch)

**Comment by IPvSean** [comment]
please open on `devel`

**Pull request closed without merging**
