### PR TITLE
Add verify playbook for rhel workshop

### PR DESCRIPTION
**Pull request by liquidat**
##### SUMMARY

Add simple verify playbook to verify deployment.

- Availabilitiy of all machines
- Right Ansible version installed on control host
- Necessary Python libs are installed on control host to run Tower modules
- Tower itself is installed
- Tower license is configured and valid (login test)
- Tower is working and provides API feedback

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

- provisioner

### CODE REVIEW

**Comment by liquidat** [comment]
@IPvSean The failed build is a fail in the teardown, so nothing related to this PR.

**Comment by liquidat** [comment]
@Spredzy Funny, here the new pipeline is not part of the build process. It worked without problems in #700 ?!
So I guess we can only merge and then figure out if this works?

**Comment by Spredzy** [comment]
@liquidat it actually is given the following screenshot

Screenshot_2020-02-26 jenkins workshops-gating-pipeline PR-687 #14

The issue is a SSL connection to tower:

```
TASK [Test access by exporting assets] *****************************************
skipping: [student2-node1]
skipping: [student2-node2]
skipping: [student2-node3]
skipping: [student1-node3]
skipping: [student1-node1]
skipping: [student1-node2]
fatal: [student1-ansible]: FAILED! => changed=false
  assets: null
  message: |-
    Could not establish a secure connection. Please add the server to your certificate authority.
    You can run this command without verifying SSL with the --insecure flag, or permanently disable verification by the config setting:

     tower-cli config verify_ssl false
  msg: Receive Failed
fatal: [student2-ansible]: FAILED! => changed=false                                                                                                                                            
  assets: null
  message: |-
    Could not establish a secure connection. Please add the server to your certificate authority.
    You can run this command without verifying SSL with the --insecure flag, or permanently disable verification by the config setting:

     tower-cli config verify_ssl false
  msg: Receive Failed
```

**Comment by liquidat** [comment]
@IPvSean

```
    There were too many requests of a given type :: Error creating new order :: too many certificates already issued for: rhdemo.io: see https://letsencrypt.org/docs/rate-limits/
```

Is this long term or a temporary fluke?

**Pull request merged**
