### PR TITLE
Add populated Tower to security

### PR DESCRIPTION
**Pull request by liquidat**
##### SUMMARY

- Add security in populate Tower role
- Add templates, inventory, project
- Add users, rights to execute templates
- Add Tower to exercise

##### ISSUE TYPE

- Feature Request

##### COMPONENT NAME

- exercises
- provisioner

### CODE REVIEW

**Comment by IPvSean** [comment]
recheck

**Comment by IPvSean** [comment]
recheck

**Comment by IPvSean** [comment]
@liquidat this is not passing linter, I think it is because of 

```
become_enabled: yes
```

**Comment by liquidat** [comment]
@IPvSean Thanks for pointing that out, fixed. Other problems seem to be due to errors in the F5 part, not related to this PR.

**Comment by IPvSean** [comment]
recheck

**Comment by liquidat** [comment]
@IPvSean All test failures are due to F5, so this commit is fine.

**Pull request merged**
