### PR TITLE
README for new windows workflow exercise

### PR DESCRIPTION
**Pull request by ffirg**
##### SUMMARY
An new optional Windows workflow exercise to close functionality gap.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME

- exercises

### CODE REVIEW

**Comment by IPvSean** [comment]
tagging @cloin and @cigamit

**Comment by IPvSean** [comment]
recheck, this has to wait on @cloin

**Comment by IPvSean** [comment]
recheck, this has to wait on @cloin

**Comment by cloin** [comment]
recheck

**Comment by ffirg** [comment]
@cloin not sure why this is failing the f5 check?

**Comment by IPvSean** [comment]
recheck

**Pull request merged**
