### PR TITLE
[WIP] Increase route53_info RR per-request item retrieval

### PR DESCRIPTION
**Pull request by jillr**
##### SUMMARY
max_items sets how many records are returned per-request. Make fewer total api requests by requesting more records at a time.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- provisioner

##### ADDITIONAL INFORMATION

For the workshop domain, `max_items: 300` should result in about 31 API calls.  (300 is the max the API will return at a time)

My laptop can't generate more than 2-3 ListResourceRecordSets calls per second. My lab server however can at times hit 5 calls per second, depending on the response set size and probably other factors.  Zuul's hardware (and network) is certainly better than mine which is likely why we only see problems in CI.  

If this doesn't improve things there should still be some things we can do in the module to catch Throttling exceptions and add artificial latency.

### CODE REVIEW

**Comment by jillr** [comment]
Right now this PR checks out and builds community.aws my working fork from here: https://github.com/jillr/community.aws/tree/1_5_0_route53_rr
That's based on stable-1.5 of the collection because ec2_instance has migrated to amazon.aws but there hasn't been a release yet and that was making things unhappy.  Once there's a version of route53_info that seems to reliably solve the throttling I'll make a clean branch/PR from main.

**Comment by IPvSean** [comment]
image
THIS IS AMAZING

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
For bonus fun, looks like we occasionally have different test jobs stomp on each other.  These were the failure timestamps for different r53 related tasks on a previous run:
2021-07-13 19:04:27.562588
2021-07-13 19:04:25.515129 
They're not exact to the second, but they're real close.  We can easily stagger when the the jobs start in zuul, but there's so many r53 tasks scattered throughout the tests that there will always be a small risk of some DNS-related tasks happening concurrently over the hour-long tests.  As such, continuing to focus on module fixes for now.

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
zuul's nightly jobs have been stuffing up the queue for the last hour.  I'm starting to suspect job concurrency might be a bigger factor, unfortunately it's not possible to test that at the moment.

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
Well that's weird.  Now I'm getting routine successes.  I have the boto stream logger capturing list_resource_record_sets calls in my branch and the tests uploading that logfile to an s3 bucket.  I'm seeing around 2-3 calls per second.  I'm also trying to catch and handle ThrottlingException but so far that code path hasn't been hit.  I wonder if the call tracing is adding the necessary latency to avoid the API limits?

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
I may have tentatively ruled out concurrency as a major factor.  What's working right now makes the info task take >2 minutes.  That might be fine, but I'd like to fuss with it a bit more, and also make the code a whole lot prettier.

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
route53 and I are not friends. what if we just added loads of task retries to the workshop roles?  :joy:

**Comment by jillr** [comment]
recheck

**Comment by jillr** [comment]
recheck

**Pull request closed without merging**
