### PR TITLE
Add collection, fixes #1196

### LINKED ISSUE #1196: ERROR! Invalid callback for stdout specified: community.general.yaml
### Area

Ansible Red Hat Enterprise Linux Workshop

### Proposed Changes

Hello for all!
Some issue with chapter workshops/exercises/ansible_rhel/1.3-playbook/
"Writing Your First Playbook".
After:
[student<X>@ansible-1 ansible-files]$ ansible-playbook apache.yml
We have an error like:
ERROR! Invalid callback for stdout specified: community.general.yaml

The workaround that we've found - change ".ansible.cfg file:
[defaults]
stdout_callback = community.general.yaml

to:
[defaults]
stdout_callback = yaml

### PR DESCRIPTION
**Pull request by liquidat**
##### SUMMARY

Adding collection required for output plugin. I chose to add the collection (and not removing the FQCN) to preserve compatibility with future Ansible versions.

Fixes #1196

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

- provisioner

### CODE REVIEW

**Comment by liquidat** [comment]
recheck

**Review by cloin — APPROVED** [review]
I like it

**Comment by goetzrieger** [comment]
It's really important we get this fixed, workshop is not working properly as is. I still don't understand how and why this got in, though.

But the cleaner fix might be to put this into a new tasks file for the control_node role as it's not too unlikely we'll have to add other collections in the future, too. Just saying. ;)

**Comment by liquidat** [comment]
@goetzrieger It is a single dedicated task right now made as a loop to add more collections of we need them.

@cloin Can you make a release?

**Pull request merged**
