### PR TITLE
Adding requirements.yml file and running instructions for workshop setup

### PR DESCRIPTION
**Pull request by rlopez133**
##### SUMMARY
This ensures that the workshops have all the collections prior to running the Ansible playbook for setup.

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request

##### COMPONENT NAME

- docs
- provisioner

##### ADDITIONAL INFORMATION
I've included the change for the doc and the requirements.yml file for provisioner.

### CODE REVIEW

**Comment by liquidat** [comment]
@rlopez133 Looks good. But isn't this more part of the one time setup, instead of something you execute each time? What do you think?

**Comment by rlopez133** [comment]
@liquidat - makes sense. I'll make the adjustment in the doc.

**Comment by rlopez133** [comment]
@liquidat - changes updated.

**Comment by liquidat** [comment]
The networking error in Zuul one looks like an artifact. But the F5 one is a problem when we don't install boinc by default, but they want to remove it by default.
@cloin  didn't you look into this?

**Comment by rlopez133** [comment]
> @rlopez133
> 
> ```
> [3519] /home/zuul/src/github.com/ansible/workshops$ /home/zuul/src/github.com/ansible/workshops/.tox/linters/bin/yamllint -s .
> ./requirements.yml
>   1:1       warning  missing document start "---"  (document-start)
>   2:1       error    wrong indentation: expected 2 but found 0  (indentation)
>   26:24     error    trailing spaces  (trailing-spaces)
> ```

Fixed.

**Pull request merged**
