### PR TITLE
Updated README.md to support additional workshop - Ansible Network 90min

### LINKED ISSUE #1926: Add 90 minute network deck to README.md
### Area

Ansible Network Automation Workshop

### Proposed Changes

https://docs.google.com/presentation/d/10QhALqWVwsZ1GYfzxAejsKmBB2QeoWo_SNkB1RnzcQo/edit?usp=sharing

This was the Network Workshop deck presented at that last NAPS workshop wednesday.

### PR DESCRIPTION
**Pull request by taruch**
##### SUMMARY
Update the README.md to support an additional Network Automation Workshop - 90 minute.
Fixes #1926

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

- docs
- decks

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by IPvSean** [comment]
@taruch are you going to also add exercises / PDF?  I just see you shared Google Slides

**Comment by taruch** [comment]
I believe I updated the README.md to include the exercises, google slides, and PDF.  I uploaded a PDF to the folder where the othere ones were, and used the same link to exercises that was used for the longer workshop.

**Comment by IPvSean** [comment]
Right now this points to the same directory of exercises, I am not sure how the student will know the difference between the 90 minute and the full workshop, there is just less slides?  Which exercises are they supposed to complete for the 90 minute?

**Comment by IPvSean** [comment]
@taruch can you provide an update?

**Pull request closed without merging**
